import "./globals.css";


export const metadata = {
  title: "FastLag inc.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-lvh text-black">
          {children}
      </body>
    </html>
  );
}
