import { cookies } from "next/headers";
import "./globals.css";


export const metadata = {
  title: "FastLag inc.",
  description: "Generated by create next app",
};



async function checkPrefered(){
  'use server'
  const theme =  cookies().get('darkMode')
  if(typeof theme === 'undefined') return ""

  return theme.value === "true" ? "dark" : ''
}

async function checkSystem(){
  const theme =  cookies().get('darkMode')
  if(typeof theme === 'undefined') return 'system'
  return ""
}

export default async function RootLayout({ children }) {
const dark = await checkPrefered()
const system = await checkSystem()


  return (
    <html lang="en" className={dark}>
      <body className={` h-lvh text-black dark:bg-black dark:text-white ${system}`}>
          {children}
      </body>
    </html>
  );
}
