import "./globals.css";


export const metadata = {
  title: "FastLag inc.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className="h-lvh text-black dark:bg-black dark:text-white ">
          {children}
      </body>
    </html>
  );
}
