// COMPONENT IMPORTS
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import { getDictionary } from "../dictionaries";
import { cookies } from "next/headers";

export const metadata = {
  title: "FastLag inc.",
  description: "Generated by create next app",
};

type PropsType = {
  children: React.ReactNode,
}

export default async function RootLayout({children}: PropsType) {
  
  const lang = cookies().get('locale')?.value
  const dict = await getDictionary(lang as string)


  return (
      <div className="h-lvh text-black">
        <div className="w-full h-full max-w-screen-xl mx-auto grid grid-cols-1 grid-rows-12">
        <Header dict={dict}/>
        {children}
        <Footer dict={dict}/>
        </div>
      </div>
  );
}
